### ISSUE TITLE
Pagination Bug

### ISSUE THREAD

**Issue by jonathanzhang99** [thecolumbialion/coffeecu#22]
We should not be loading all of the pictures/profiles at once on the home page. Instead, we can implement a simple pagination that fetches and displays more images on user scroll or with a dedicated "new page" button.

**Comment by wessilfie** [comment]
We originally had a load more button that did this but people didn’t like it/stop looking when it’s there which is why we moved to auto load. It’s the same concept, it just automates clicking that button as you get near it

**Comment by jonathanzhang99** [comment]
Ah i see what you mean. I think there might be a bug with how auto-load works then. Even if I don't scroll all the way to the end of the currently displayed section, the page seems to load more profiles.

**Comment by jimmyro** [comment]
This isn't a bug, it's supposed to work that way
