### ISSUE TITLE
routing issues: /admin doesn't redirect, /user/(nonexistent id) doesn't 404

### ISSUE THREAD

**Issue by jimmyro** [thecolumbialion/coffeecu#35]
/admin doesn't redirect if user is not admin, only displays blank page.  should redirect to home or display some kind of 403 page

/user/(nonexistent id) should show the 404 page -- we already have a funny graphic for this, I think the redirect just isn't set up.

**Comment by wessilfie** [comment]
needs to be fixed bc it wasnt fully working

**Comment by jimmyro** [comment]
#36
