### ISSUE TITLE
hyperlink goes off the page

### ISSUE THREAD

**Issue by lesley2958** [thecolumbialion/coffeecu#48]
<img width="407" alt="screen shot 2018-02-16 at 6 37 15 pm" src="https://user-images.githubusercontent.com/9807841/36334051-86b2e1d6-1348-11e8-9456-6bcc7a31179f.png">

**Comment by 2dev9** [comment]
This should be fixed by PR #52

**Comment by 2dev9** [comment]
Resolved by #52
